import { Role } from '../types';
import type { RoutesConfig } from '../types';

// ─────────────────────────────────────────────────────────────────────────────
// AL-Mizan API Gateway — Route Configuration
// ─────────────────────────────────────────────────────────────────────────────
// Each service defines:
//   url:         Target microservice base URL
//   path:        API path prefix (mounted under gateway.prefix + gateway.version)
//   auth:        Default auth requirement for all routes under this service
//   public:      Whether unauthenticated access is allowed (overrides auth)
//   roles:       Allowed roles (empty = any authenticated user)
//   rateLimit:   Per-route rate limit override (requests per window)
//   routes:      Per-endpoint overrides (method + path + auth/roles/public)
// ─────────────────────────────────────────────────────────────────────────────

export const routesConfig: RoutesConfig = {
  gateway: {
    prefix: '/api',
    version: 'v1',
  },

  services: {
    // ─── Auth Service ─────────────────────────────────────────────────────────
    auth: {
      url: process.env.AUTH_SERVICE_URL || 'http://localhost:3001',
      path: '/auth',
      auth: false,
      description: 'Authentication, tokens and session management',
      routes: [
        {
          path: '/register',
          method: 'POST',
          auth: false,
          public: true,
          description: 'User registration',
        },
        {
          path: '/login',
          method: 'POST',
          auth: false,
          public: true,
          description: 'User login',
        },
        {
          path: '/refresh',
          method: 'POST',
          auth: false,
          public: true,
          description: 'Refresh access token',
        },
        {
          path: '/logout',
          method: 'POST',
          auth: true,
          description: 'User logout',
        },
        {
          path: '/logout-all',
          method: 'POST',
          auth: true,
          description: 'Logout from all active sessions',
        },
        {
          path: '/me',
          method: 'GET',
          auth: true,
          description: 'Get current authenticated user',
        },
        {
          path: '/sessions',
          method: 'GET',
          auth: true,
          description: 'List active sessions',
        },
        {
          path: '/sessions/:id',
          method: 'DELETE',
          auth: true,
          description: 'Revoke one active session',
        },
        {
          path: '/users/user-roles/:userId',
          method: 'GET',
          auth: true,
          description: 'List roles assigned to a user (via auth proxy)',
        },
        {
          path: '/forgot-password',
          method: 'POST',
          auth: false,
          public: true,
          description: 'Request password reset',
        },
        {
          path: '/verify-token',
          method: 'POST',
          auth: false,
          public: true,
          description: 'Verify password reset token',
        },
        {
          path: '/reset-password',
          method: 'POST',
          auth: false,
          public: true,
          description: 'Reset password using token',
        },
        {
          path: '/change-password',
          method: 'POST',
          auth: true,
          description: 'Change password (authenticated user)',
        },
      ],
    },

        // ─── Users Service ───────────────────────────────────────────────────────
    profiles: {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/profiles',
      auth: true,
      description: 'User profiles',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.ADMIN] },
        { path: '/user/:userId', method: 'GET', auth: true },
        { path: '/user/:userId', method: 'PATCH', auth: true },
        { path: '/:id', method: 'GET', auth: true },
        { path: '/:id', method: 'PATCH', auth: true },
        { path: '/:id', method: 'DELETE', auth: true, roles: [Role.ADMIN] },
      ],
    },
    organisations: {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/organisations',
      auth: true,
      description: 'Organisations',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.SERVICE_CONTRACTANT, Role.OPERATEUR_ECONOMIQUE] },
        { path: '', method: 'GET', auth: true },
        { path: '/:id', method: 'GET', auth: true },
        { path: '/:id', method: 'PATCH', auth: true, roles: [Role.ADMIN, Role.SERVICE_CONTRACTANT] },
        { path: '/:id/verify', method: 'PATCH', auth: true, roles: [Role.ADMIN] },
        { path: '/:id', method: 'DELETE', auth: true, roles: [Role.ADMIN] },
      ],
    },
    'services-contractants': {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/services-contractants',
      auth: true,
      description: 'Services contractants',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.ADMIN] },
        { path: '', method: 'GET', auth: true },
        { path: '/profile', method: 'GET', auth: true, roles: [Role.SERVICE_CONTRACTANT] },
        { path: '/profile', method: 'PUT', auth: true, roles: [Role.SERVICE_CONTRACTANT] },
        { path: '/:id', method: 'GET', auth: true },
        { path: '/:id', method: 'PATCH', auth: true, roles: [Role.ADMIN] },
        { path: '/:id', method: 'DELETE', auth: true, roles: [Role.ADMIN] },
      ],
    },
    'operateurs-economiques': {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/operateurs-economiques',
      auth: true,
      description: 'Operateurs economiques',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.ADMIN] },
        { path: '', method: 'GET', auth: true },
        { path: '/profile', method: 'GET', auth: true, roles: [Role.OPERATEUR_ECONOMIQUE] },
        { path: '/profile', method: 'PUT', auth: true, roles: [Role.OPERATEUR_ECONOMIQUE] },
        { path: '/:id', method: 'GET', auth: true },
        { path: '/:id', method: 'PATCH', auth: true, roles: [Role.ADMIN] },
        { path: '/:id/blacklist', method: 'PATCH', auth: true, roles: [Role.ADMIN] },
        { path: '/:id/unblacklist', method: 'PATCH', auth: true, roles: [Role.ADMIN] },
        { path: '/:id', method: 'DELETE', auth: true, roles: [Role.ADMIN] },
      ],
    },
    roles: {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/roles',
      auth: true,
      description: 'RBAC roles',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.ADMIN] },
        { path: '', method: 'GET', auth: true, roles: [Role.ADMIN] },
        { path: '/seed-defaults', method: 'POST', auth: true, roles: [Role.ADMIN] },
      ],
    },
    'user-roles': {
      url: process.env.USERS_SERVICE_URL || 'http://localhost:3002',
      path: '/user-roles',
      auth: true,
      description: 'User roles',
      routes: [
        { path: '', method: 'POST', auth: true, roles: [Role.ADMIN] },
        { path: '/:userId', method: 'GET', auth: true, roles: [Role.ADMIN] },
        { path: '/:userId/:roleId', method: 'DELETE', auth: true, roles: [Role.ADMIN] },
      ],
    },

// ─── Appels d'Offres (Tenders) Service ────────────────────────────────────
    tenders: {
      url: process.env.TENDERS_SERVICE_URL || 'http://localhost:8003',
      path: '/appels-offres',
      auth: true,
      roles: [Role.SERVICE_CONTRACTANT],
      pathRewrite: {
        '^/api/v1/appels-offres/avis-ao$': '/api/v1/avis-ao',
        '^/api/v1/appels-offres/avis-ao/(.*)$': '/api/v1/avis-ao/$1',
        '^/api/v1/appels-offres/attributions$': '/api/v1/attributions',
        '^/api/v1/appels-offres/attributions/(.*)$': '/api/v1/attributions/$1',
        '^/api/v1/appels-offres/marches$': '/api/v1/marches',
        '^/api/v1/appels-offres/marches/(.*)$': '/api/v1/marches/$1',
        '^/api/v1/appels-offres/gre-a-gre/([^/]+)/valider$': '/api/v1/appels-offres/gre-a-gre/$1/valider',
        '^/api/v1/appels-offres/([^/]+)/gre-a-gre/soumettre$': '/api/v1/appels-offres/$1/gre-a-gre/soumettre',
        '^/api/v1/appels-offres/([^/]+)/criteres-evaluation/([^/]+)$': '/api/v1/appels-offres/$1/criteres-evaluation/$2',
        '^/api/v1/appels-offres/([^/]+)/criteres-evaluation$': '/api/v1/appels-offres/$1/criteres-evaluation',
        '^/api/v1/appels-offres/([^/]+)/criteres-eligibilite/([^/]+)$': '/api/v1/appels-offres/$1/criteres-eligibilite/$2',
        '^/api/v1/appels-offres/([^/]+)/criteres-eligibilite$': '/api/v1/appels-offres/$1/criteres-eligibilite',
        '^/api/v1/appels-offres/([^/]+)/statut$': '/api/v1/appels-offres/$1/statut',
        '^/api/v1/appels-offres/([^/]+)/cdc/download$': '/api/v1/appels-offres/$1/cdc/download',
        '^/api/v1/appels-offres$': '/api/v1/appels-offres',
        '^/api/v1/appels-offres/(.*)$': '/api/v1/appels-offres/$1',
      },
      description: 'Tender lifecycle, lots, CDC, criteria, attribution',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: false,
          public: true,
          description: 'List published tenders (public access)',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Get tender details (public access)',
        },
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Create a new tender',
        },
        {
          path: '/:id',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update tender',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete tender',
        },
        {
          path: '/:id/lots',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Add lots to tender',
        },
        {
          path: '/:id/lots',
          method: 'GET',
          auth: false,
          public: true,
          description: 'List lots for a tender',
        },
        {
          path: '/:id/criteres-evaluation',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Define evaluation criteria',
        },
        {
          path: '/:id/criteres-evaluation',
          method: 'GET',
          auth: false,
          public: true,
          description: 'List evaluation criteria',
        },
        {
          path: '/:id/criteres-evaluation/:criteriaId',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Get one evaluation criterion',
        },
        {
          path: '/:id/criteres-evaluation/:criteriaId',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update one evaluation criterion',
        },
        {
          path: '/:id/criteres-evaluation/:criteriaId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete one evaluation criterion',
        },
        {
          path: '/:id/criteres-eligibilite',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Define eligibility criteria',
        },
        {
          path: '/:id/criteres-eligibilite',
          method: 'GET',
          auth: false,
          public: true,
          description: 'List eligibility criteria',
        },
        {
          path: '/:id/criteres-eligibilite/:criteriaId',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Get one eligibility criterion',
        },
        {
          path: '/:id/criteres-eligibilite/:criteriaId',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update one eligibility criterion',
        },
        {
          path: '/:id/criteres-eligibilite/:criteriaId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete one eligibility criterion',
        },
        {
          path: '/:id/statut',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update tender status',
        },
        {
          path: '/:id/gre-a-gre/soumettre',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Submit sole-source request',
        },
        {
          path: '/gre-a-gre/:demandeId/valider',
          method: 'PATCH',
          auth: true,
          roles: [Role.CONTROLEUR],
          description: 'Validate/reject sole-source request',
        },
        {
          path: '/:id/cdc',
          method: 'GET',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE, Role.SERVICE_CONTRACTANT],
          description: 'Download cahier des charges',
        },
        {
          path: '/:id/cdc',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Upload/link cahier des charges',
        },
        {
          path: '/:id/cdc/download',
          method: 'GET',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE, Role.SERVICE_CONTRACTANT],
          description: 'Download cahier des charges via secure URL',
        },
        {
          path: '/avis-ao',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Create a regulatory notice',
        },
        {
          path: '/avis-ao',
          method: 'GET',
          auth: false,
          public: true,
          description: 'List regulatory notices',
        },
        {
          path: '/avis-ao/:id',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Get one regulatory notice',
        },
        {
          path: '/avis-ao/:id',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update a regulatory notice',
        },
        {
          path: '/avis-ao/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete a regulatory notice',
        },
        {
          path: '/attributions',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Create an attribution decision',
        },
        {
          path: '/attributions',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.CONTROLEUR, Role.ADMIN],
          description: 'List attribution decisions',
        },
        {
          path: '/attributions/:id',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.CONTROLEUR, Role.ADMIN],
          description: 'Get an attribution decision',
        },
        {
          path: '/attributions/:id',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update an attribution decision',
        },
        {
          path: '/attributions/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete an attribution decision',
        },
        {
          path: '/marches',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Create a marche record',
        },
        {
          path: '/marches',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.CONTROLEUR, Role.ADMIN],
          description: 'List marche records',
        },
        {
          path: '/marches/statistiques',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Get clotured markets statistics',
        },
        {
          path: '/marches/:id',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.CONTROLEUR, Role.ADMIN],
          description: 'Get a marche record',
        },
        {
          path: '/marches/:id',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Update a marche record',
        },
        {
          path: '/marches/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Delete a marche record',
        },
        {
          path: '/:aoId/clarifications',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Submit a clarification request',
        },
        {
          path: '/:aoId/clarifications',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Get clarification questions and answers',
        },
        {
          path: '/:aoId/clarifications/:id/repondre',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT],
          description: 'Respond to a clarification request',
        },
      ],
    },

    // ─── Soumissions (Submissions) Service ───────────────────────────────────
    submissions: {
      url: process.env.SUBMISSIONS_SERVICE_URL || 'http://localhost:8004',
      path: '/soumissions',
      auth: true,
      forwardAuthInBody: true,
      roles: [
        Role.OPERATEUR_ECONOMIQUE,
        Role.MEMBRE_COMMISSION,
        Role.ADMIN,
        Role.CONTROLEUR,
      ],
      description: 'Electronic bid submission with E2EE',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Create submission draft',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'List own submissions',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          roles: [
            Role.OPERATEUR_ECONOMIQUE,
            Role.MEMBRE_COMMISSION,
            Role.ADMIN,
            Role.CONTROLEUR,
          ],
          description: 'Get one submission details',
        },
        {
          path: '/appel-offre/:aoId',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN, Role.CONTROLEUR],
          description: 'List submissions by appel d\'offre',
        },
        {
          path: '/:id/valider',
          method: 'PUT',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Validate and submit one submission',
        },
        {
          path: '/:id/statut',
          method: 'PUT',
          auth: true,
          roles: [Role.ADMIN, Role.MEMBRE_COMMISSION],
          description: 'Update submission status',
        },
        {
          path: '/:soumissionId/offre-technique',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Upload technical offer',
        },
        {
          path: '/:soumissionId/offre-technique',
          method: 'GET',
          auth: true,
          roles: [
            Role.OPERATEUR_ECONOMIQUE,
            Role.MEMBRE_COMMISSION,
            Role.ADMIN,
            Role.CONTROLEUR,
          ],
          description: 'Get technical offer',
        },
        {
          path: '/:soumissionId/offre-financiere',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Upload encrypted financial offer',
        },
        {
          path: '/:soumissionId/offre-financiere',
          method: 'GET',
          auth: true,
          roles: [
            Role.OPERATEUR_ECONOMIQUE,
            Role.MEMBRE_COMMISSION,
            Role.ADMIN,
            Role.CONTROLEUR,
          ],
          description: 'Get encrypted financial offer',
        },
        {
          path: '/:soumissionId/caution',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Upload caution document',
        },
        {
          path: '/:soumissionId/caution',
          method: 'GET',
          auth: true,
          roles: [
            Role.OPERATEUR_ECONOMIQUE,
            Role.MEMBRE_COMMISSION,
            Role.ADMIN,
            Role.CONTROLEUR,
          ],
          description: 'Get caution document',
        },
      ],
    },

    // ─── Soumissions: Offres Financières (Dechiffrement) ────────────────────
    submissionsFinancial: {
      url: process.env.SUBMISSIONS_SERVICE_URL || 'http://localhost:8004',
      path: '/offres-financieres',
      auth: true,
      forwardAuthInBody: true,
      roles: [Role.MEMBRE_COMMISSION],
      description: 'Financial offers decryption workflow',
      routes: [
        {
          path: '/dechiffrer/:aoId',
          method: 'POST',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION],
          description: 'Decrypt financial offers for an appel d\'offre',
        },
      ],
    },

    // ─── Soumissions: Clés de Chiffrement ────────────────────────────────────
    submissionsKeys: {
      url: process.env.SUBMISSIONS_SERVICE_URL || 'http://localhost:8004',
      path: '/cles-chiffrement',
      auth: true,
      forwardAuthInBody: true,
      roles: [Role.ADMIN],
      description: 'RSA/Shamir key generation and public key retrieval',
      routes: [
        {
          path: '/:aoId',
          method: 'POST',
          auth: true,
          roles: [Role.ADMIN],
          description: 'Generate encryption keys for an appel d\'offre',
        },
        {
          path: '/:aoId/publique',
          method: 'GET',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE, Role.ADMIN],
          description: 'Get public key for an appel d\'offre',
        },
      ],
    },

    // ─── Documents Service ───────────────────────────────────────────────────
    documents: {
      url: process.env.DOCUMENTS_SERVICE_URL || 'http://localhost:8005',
      path: '/documents',
      auth: true,
      pathRewrite: {
        '^/api/v1/documents/(.*)$': '/api/documents/$1',
        '^/api/v1/documents$': '/api/documents',
      },
      description: 'File storage, admin docs, OCR/NLP pipeline',
      routes: [
        {
          path: '/upload',
          method: 'POST',
          auth: true,
          description: 'Upload a document',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          description: 'Download a document',
        },
        {
          path: '/:id/download',
          method: 'GET',
          auth: true,
          description: 'Get presigned download URL',
        },
        {
          path: '/:id/integrity',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Verify document SHA-256 integrity',
        },
        {
          path: '/administrative/:submissionId',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Attach administrative piece to a submission',
        },
        {
          path: '/administrative/:submissionId',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'List administrative pieces by submission',
        },
        {
          path: '/administrative/piece/:pieceId/validate',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Validate or invalidate administrative piece',
        },
        {
          path: '/:id/verify-certificate',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'Verify PKI certificate on a document',
        },
      ],
    },

    // ─── Evaluations Service ─────────────────────────────────────────────────
    evaluations: {
      url: process.env.EVALUATIONS_SERVICE_URL || 'http://localhost:8008',
      path: '/evaluations',
      auth: true,
      description: 'Offer scoring, grading, and ranking workflows',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'List evaluations with filters and pagination',
        },
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Create a new evaluation',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Get evaluation details',
        },
        {
          path: '/:id',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'Update evaluation',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Delete evaluation',
        },
        {
          path: '/:id/statut',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'Change evaluation status',
        },
        {
          path: '/:id/criteres',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'List evaluation criteria',
        },
        {
          path: '/:id/criteres',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Add evaluation criterion',
        },
        {
          path: '/:id/criteres/:criterionId',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Update evaluation criterion',
        },
        {
          path: '/:id/criteres/:criterionId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Delete evaluation criterion',
        },
        {
          path: '/:id/soumissions',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'List submissions linked to evaluation',
        },
        {
          path: '/:id/soumissions',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Register submission in evaluation',
        },
        {
          path: '/:id/soumissions/:submissionId',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Update evaluation submission metadata',
        },
        {
          path: '/:id/soumissions/:submissionId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION],
          description: 'Remove submission from evaluation',
        },
        {
          path: '/:id/soumissions/:submissionId/notes',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'List notes for a submission',
        },
        {
          path: '/:id/soumissions/:submissionId/notes',
          method: 'POST',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION],
          description: 'Create or update evaluator note',
        },
        {
          path: '/:id/recalculer-scores',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'Recalculate scores and ranking',
        },
        {
          path: '/:id/classement',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Get evaluation ranking',
        },
        {
          path: '/:id/rapport',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.ADMIN],
          description: 'Generate final evaluation report',
        },
        {
          path: '/:id/rapport',
          method: 'GET',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Get latest evaluation report',
        },
      ],
    },

    // ─── Commissions: Evaluation ────────────────────────────────────────────
    commissionsEvaluation: {
      url: process.env.COMMISSIONS_SERVICE_URL || 'http://localhost:8007',
      path: '/commissions-evaluation',
      auth: true,
      roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
      description: 'Commission d evaluation management',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: true,
          description: 'List evaluation commissions',
        },
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Create evaluation commission',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          description: 'Get evaluation commission',
        },
        {
          path: '/:id',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Update evaluation commission',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Delete evaluation commission',
        },
        {
          path: '/:id/statut',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Change evaluation commission status',
        },
        {
          path: '/:id/membres',
          method: 'GET',
          auth: true,
          description: 'List evaluation commission members',
        },
        {
          path: '/:id/membres',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Add evaluation commission member',
        },
        {
          path: '/:id/membres/:membreId',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Update evaluation commission member',
        },
        {
          path: '/:id/membres/:membreId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Remove evaluation commission member',
        },
        {
          path: '/:id/export-pdf',
          method: 'GET',
          auth: true,
          description: 'Export evaluation commission PDF',
        },
      ],
    },

    // ─── Commissions: Marche ────────────────────────────────────────────────
    commissionsMarche: {
      url: process.env.COMMISSIONS_SERVICE_URL || 'http://localhost:8007',
      path: '/commissions-marche',
      auth: true,
      roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
      description: 'Commission de marche management',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: true,
          description: 'List market commissions',
        },
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Create market commission',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          description: 'Get market commission',
        },
        {
          path: '/:id',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Update market commission',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Delete market commission',
        },
        {
          path: '/:id/statut',
          method: 'PATCH',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Change market commission status',
        },
        {
          path: '/:id/membres',
          method: 'GET',
          auth: true,
          description: 'List market commission members',
        },
        {
          path: '/:id/membres',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Add market commission member',
        },
        {
          path: '/:id/membres/:membreId',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Update market commission member',
        },
        {
          path: '/:id/membres/:membreId',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Remove market commission member',
        },
        {
          path: '/:id/deliberation',
          method: 'POST',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Set deliberation PV',
        },
        {
          path: '/:id/deliberation',
          method: 'GET',
          auth: true,
          description: 'Get deliberation PV',
        },
        {
          path: '/:id/attribution',
          method: 'PATCH',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Attribuer marche',
        },
        {
          path: '/:id/export-pdf',
          method: 'GET',
          auth: true,
          description: 'Export market commission PDF',
        },
      ],
    },

    // ─── Commissions: Seances d Ouverture ──────────────────────────────────
    commissionsSeancesOuverture: {
      url: process.env.COMMISSIONS_SERVICE_URL || 'http://localhost:8007',
      path: '/seances-ouverture',
      auth: true,
      roles: [Role.SERVICE_CONTRACTANT, Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
      description: 'Seances d ouverture management',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: true,
          description: 'List opening sessions',
        },
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Create opening session',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          description: 'Get opening session',
        },
        {
          path: '/:id',
          method: 'PUT',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Update opening session',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          roles: [Role.SERVICE_CONTRACTANT, Role.ADMIN],
          description: 'Delete opening session',
        },
        {
          path: '/:id/demarrer',
          method: 'PATCH',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Demarrer opening session',
        },
        {
          path: '/:id/terminer',
          method: 'PATCH',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Terminer opening session',
        },
        {
          path: '/:id/pv',
          method: 'POST',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Generate opening PV',
        },
        {
          path: '/:id/pv',
          method: 'GET',
          auth: true,
          description: 'Download opening PV',
        },
        {
          path: '/:id/resultats',
          method: 'GET',
          auth: true,
          description: 'List opening results',
        },
        {
          path: '/:id/resultats',
          method: 'POST',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Add opening result',
        },
        {
          path: '/:id/resultats/:resultatId',
          method: 'PUT',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Update opening result',
        },
        {
          path: '/:id/resultats/:resultatId',
          method: 'DELETE',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR, Role.ADMIN],
          description: 'Delete opening result',
        },
      ],
    },

    // ─── Commissions: Health ───────────────────────────────────────────────
    commissionsHealth: {
      url: process.env.COMMISSIONS_SERVICE_URL || 'http://localhost:8007',
      path: '/commission-health',
      auth: false,
      public: true,
      pathRewrite: {
        '^/api/v1/commission-health$': '/health',
      },
      description: 'Commission service health check',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Health check endpoint',
        },
      ],
    },

    // ─── Recours Service ─────────────────────────────────────────────────────
    appeals: {
      url: process.env.APPEALS_SERVICE_URL || 'http://localhost:8009',
      path: '/recours',
      auth: true,
      pathRewrite: {
        '^/api/v1/recours/(.*)$': '/recours-service/v1/recours/$1',
        '^/api/v1/recours$': '/recours-service/v1/recours',
      },
      description: 'Recours filing, examination, and decisions',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Deposer un recours',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR, Role.MEMBRE_COMMISSION],
          description: 'Lister les recours',
        },
        {
          path: '/statistiques',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR, Role.MEMBRE_COMMISSION],
          description: 'Statistiques des recours',
        },
        {
          path: '/delais-expires',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR, Role.MEMBRE_COMMISSION],
          description: 'Recours avec delais expires',
        },
        {
          path: '/operateur/:operateurId',
          method: 'GET',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE, Role.ADMIN, Role.CONTROLEUR],
          description: 'Recours d un operateur economique',
        },
        {
          path: '/appel-offre/:appelOffreId',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR, Role.MEMBRE_COMMISSION, Role.SERVICE_CONTRACTANT],
          description: 'Recours par appel d offre',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR, Role.MEMBRE_COMMISSION, Role.OPERATEUR_ECONOMIQUE],
          description: 'Detail d un recours',
        },
        {
          path: '/:id',
          method: 'PATCH',
          auth: true,
          roles: [Role.OPERATEUR_ECONOMIQUE],
          description: 'Modifier un recours',
        },
        {
          path: '/:id/examiner',
          method: 'PATCH',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR],
          description: 'Ouvrir l examen d un recours',
        },
        {
          path: '/:id/statuer',
          method: 'PATCH',
          auth: true,
          roles: [Role.MEMBRE_COMMISSION, Role.CONTROLEUR],
          description: 'Statuer sur un recours',
        },
      ],
    },

    // ─── Recours: Health ───────────────────────────────────────────────────
    appealsHealth: {
      url: process.env.APPEALS_SERVICE_URL || 'http://localhost:8009',
      path: '/recours-health',
      auth: false,
      public: true,
      pathRewrite: {
        '^/api/v1/recours-health$': '/recours-service/v1/health',
      },
      description: 'Recours service health check',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Health check endpoint',
        },
      ],
    },

    // ─── Audit Service ──────────────────────────────────────────────────────
    audit: {
      url: process.env.AUDIT_SERVICE_URL || 'http://localhost:3009',
      path: '/audit',
      auth: true,
      description: 'Immutable audit logs, IA incident monitoring',
      routes: [
        {
          path: '/logs',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Search audit logs',
        },
        {
          path: '/activities',
          method: 'GET',
          auth: true,
          description: 'Get activity feed for dashboard',
        },
        {
          path: '/integrity',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN],
          description: 'Verify hash chain integrity',
        },
        {
          path: '/incidents',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'List AI incidents',
        },
        {
          path: '/incidents/:id/resolve',
          method: 'PUT',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Resolve AI incident',
        },
      ],
    },

    // ─── Notifications Service ──────────────────────────────────────────────
    notifications: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/notifications',
      auth: true,
      pathRewrite: {
        '^/api/v1/notifications/(.*)$': '/notification-service/v1/notifications/$1',
        '^/api/v1/notifications$': '/notification-service/v1/notifications',
      },
      description: 'Email, SMS and push notifications',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          description: 'Create and dispatch notification',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'List all notifications (admin)',
        },
        {
          path: '/mes-notifications',
          method: 'GET',
          auth: true,
          description: 'List my notifications',
        },
        {
          path: '/non-lues/count',
          method: 'GET',
          auth: true,
          description: 'Count unread notifications',
        },
        {
          path: '/marquer-toutes-lues',
          method: 'PATCH',
          auth: true,
          description: 'Mark all notifications as read',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          description: 'Get notification details',
        },
        {
          path: '/:id/lire',
          method: 'PATCH',
          auth: true,
          description: 'Mark one notification as read',
        },
      ],
    },

    // ─── Notifications: Alertes IA ─────────────────────────────────────────
    notificationsIaAlerts: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/alertes-ia',
      auth: true,
      pathRewrite: {
        '^/api/v1/alertes-ia/(.*)$': '/notification-service/v1/alertes-ia/$1',
        '^/api/v1/alertes-ia$': '/notification-service/v1/alertes-ia',
      },
      description: 'IA alerts and incident handling',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          description: 'Create IA alert',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'List IA alerts',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Get IA alert details',
        },
        {
          path: '/:id/acquitter',
          method: 'PATCH',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Acknowledge IA alert',
        },
        {
          path: '/:id/resoudre',
          method: 'PATCH',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Resolve IA alert',
        },
      ],
    },

    // ─── Notifications: Rapports IA ────────────────────────────────────────
    notificationsIaReports: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/rapports-ia',
      auth: true,
      pathRewrite: {
        '^/api/v1/rapports-ia/(.*)$': '/notification-service/v1/rapports-ia/$1',
        '^/api/v1/rapports-ia$': '/notification-service/v1/rapports-ia',
      },
      description: 'IA periodic reports',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          description: 'Create and send IA report',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'List IA reports',
        },
        {
          path: '/:id',
          method: 'GET',
          auth: true,
          roles: [Role.ADMIN, Role.CONTROLEUR],
          description: 'Get IA report details',
        },
      ],
    },

    // ─── Notifications: Device Tokens ──────────────────────────────────────
    notificationsDeviceTokens: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/device-tokens',
      auth: true,
      pathRewrite: {
        '^/api/v1/device-tokens/(.*)$': '/notification-service/v1/device-tokens/$1',
        '^/api/v1/device-tokens$': '/notification-service/v1/device-tokens',
      },
      description: 'FCM device token management',
      routes: [
        {
          path: '/',
          method: 'POST',
          auth: true,
          description: 'Register device token',
        },
        {
          path: '/',
          method: 'GET',
          auth: true,
          description: 'List my device tokens',
        },
        {
          path: '/:id',
          method: 'DELETE',
          auth: true,
          description: 'Deactivate device token',
        },
      ],
    },

    // ─── Notifications: Preferences ────────────────────────────────────────
    notificationsPreferences: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/preferences',
      auth: true,
      pathRewrite: {
        '^/api/v1/preferences/(.*)$': '/notification-service/v1/preferences/$1',
        '^/api/v1/preferences/$': '/notification-service/v1/preferences/',
        '^/api/v1/preferences$': '/notification-service/v1/preferences',
      },
      description: 'Notification preferences',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: true,
          description: 'Get my notification preferences',
        },
        {
          path: '/',
          method: 'PATCH',
          auth: true,
          description: 'Update my notification preferences',
        },
      ],
    },

    // ─── AI Orchestrator ─────────────────────────────────────────────────────
    aiOrchestrator: {
      url: process.env.AI_ORCHESTRATOR_URL || 'http://ai-orchestrator:3099',
      path: '/ai',
      auth: true,
      pathRewrite: {
        '^/api/v1/ai/(.*)$': '/ai/$1',
        '^/api/v1/ai$': '/ai',
      },
      description: 'AI-assisted features (CDC draft generation)',
      routes: [],
    },

    // ─── Notifications: Health ─────────────────────────────────────────────
    notificationsHealth: {
      url: process.env.NOTIFICATIONS_SERVICE_URL || 'http://localhost:8010',
      path: '/notification-health',
      auth: false,
      public: true,
      pathRewrite: {
        '^/api/v1/notification-health$': '/notification-service/v1/health',
      },
      description: 'Notification service health check',
      routes: [
        {
          path: '/',
          method: 'GET',
          auth: false,
          public: true,
          description: 'Health check endpoint',
        },
      ],
    },
  },
};
